spring:
  datasource:
    url: jdbc:hsqldb:file:~/.ikenga/db/db;hsqldb.write_delay=true;shutdown=true
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:   
        hbm2ddl:
          auto: update